### System dynamic variables :
### {{$guid}}
### {{$randomInt min max}}
### {{$timestamp [offset option]}}
### {{$datetime rfc1123|iso8601 [offset option]}}
### {{$localDatetime rfc1123|iso8601 [offset option]}}
### {{$processEnv [%]envVarName}}
### {{$dotenv [%]variableName}}
### {{$aadToken [new] [public|cn|de|us|ppe] [<domain|tenantId>] [aud:<domain|tenantId>]}}

@customerId={{$guid}}
@isActive=true
@GetCustomerRequest= CustomerId={{customerId}}&IsActive={{isActive}}
GET https://localhost:52562/api/customers?{{GetCustomerRequest}}
Accept-Language: fr-FR,en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json